apiVersion: v1
kind: Service
metadata:
  name: purple
spec:
  ports:
  - port: 8087
    targetPort: http
    protocol: TCP
    name: http
  selector:
    color: purple
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: orange
spec:
  ports:
  - port: 8087
    targetPort: http
    protocol: TCP
    name: http
  selector:
    color: orange
  type: LoadBalancer